language: python
python:
  - "3.5"
install:
  - pip install tox
script: tox -e py35
notifications:
  email:
    recipients:
      - dev+tests-reports@wazo.community
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
