language: python
python:
  - "3.4"
script: tox
notifications:
  email:
    recipients:
      - dev+tests-reports@wazo.community
    on_success: change
    on_failure: change
branches:
  only:
    - master
sudo: false
