sync:
  image: n3llyb0y/wait
  links:
    - plugind
    - consul
    - rabbitmq
    - auth
  environment:
    PORTS: "5672 8500 9497 9503"
plugind:
  cap_add:
    - LINUX_IMMUTABLE
  image: "wazopbx/wazo-plugind"
  links:
    - consul
    - rabbitmq
    - auth
  volumes:
    - "./etc/wazo-plugind/conf.d/consul.yml:/etc/wazo-plugind/conf.d/consul.yml"
    - "./etc/wazo-plugind/conf.d/rabbitmq.yml:/etc/wazo-plugind/conf.d/rabbitmq.yml"
    - "./etc/wazo-plugind/conf.d/auth.yml:/etc/wazo-plugind/conf.d/auth.yml"
  environment:
    - XIVO_UUID=cd030e68-ace9-4ad4-bc4e-13c8dec67898
  ports:
    - "9503"
auth:
  image: "wazopbx/xivo-auth-mock"
  ports:
    - "9497"
rabbitmq:
  image: "rabbitmq"
  ports:
    - 5672
consul:
  image: "consul"
  command: consul agent -server -dev -client=0.0.0.0
  ports:
    - "8500"
